import type { TaskModel } from "../models/TaskModel";

export function getNextCycleType(currentCycle: number): TaskModel["type"] {
    if (currentCycle % 8 === 0) return "longRest";
    if (currentCycle % 2 === 0) return "shortRest";
    return "workTime";
}

// Usa o currentCycle como param. e utiliza-a para fazer uma lógica numérica...
// Se / por 8 e a sobra = 0 -> descanso logo...
// Se / por 2 e a sobra = 0 -> descanso curto...
// Se nenhum -> foco...